services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro # update it to be in the OS /etc/traefik
      - ./certs:/var/traefik/certs:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik-dashboard.app.trustin.tech`)"
      - "traefik.http.routers.traefik-dashboard-http.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard-https.tls=true"
      - "traefik.http.routers.traefik-dashboard-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik-dashboard.app.trustin.tech`)"
    networks:
      proxy:

networks:
  proxy:
    external: true
