secrets:
  cf-dns-api-token:
    file: ./.secrets/cf-dns-api-token
  cf-app-trustin-tech-tunnel-api-token:
    file: ./.secrets/cf-app-trustin-tech-tunnel-api-token

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    secrets:
      - cf-app-trustin-tech-tunnel-api-token
    environment:
      - TUNNEL_TOKEN=/run/secrets/cf-app-trustin-tech-tunnel-api-token
    networks:
      proxy:
    command: ["tunnel", "--no-autoupdate", "run"]

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    secrets:
      - cf-dns-api-token
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - 80:80
      - 443:443
    # env_file:
    #   - .env
    environment:
      - CF_DNS_API_TOKEN=/run/secrets/cf-dns-api-token
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro # update it to be in the OS /etc/traefik
      - ./certs:/var/traefik/certs:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard-http.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik-dashboard.app.trustin.tech`)"
      - "traefik.http.routers.traefik-dashboard-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard-https.rule=Host(`traefik-dashboard.app.trustin.tech`)"
      - "traefik.http.routers.traefik-dashboard-https.tls=true"
      - "traefik.http.routers.traefik-dashboard-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-dashboard-https.tls.domains[0].main=app.trustin.tech"
      - "traefik.http.routers.traefik-dashboard-https.tls.domains[0].sans=*.app.trustin.tech"
      - "traefik.http.routers.traefik-dashboard-https.service=api@internal"
    networks:
      proxy:

networks:
  proxy:
    external: true
